src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $appointment_time = null;

    #[ORM\Column(length: 255)]
    private ?int $reservation_code = null;

    #[ORM\Column(length: 255)]
    private ?string $state = null;

    #[ORM\ManyToOne(inversedBy: 'customers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Specialist $specialist = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAppointmentTime(): ?\DateTimeInterface
    {
        return $this->appointment_time;
    }

    public function setAppointmentTime(\DateTimeInterface $appointment_time): static
    {
        $this->appointment_time = $appointment_time;

        return $this;
    }

    public function getReservationCode(): ?string
    {
        return $this->reservation_code;
    }

    public function setReservationCode(string $reservation_code): static
    {
        $this->reservation_code = $reservation_code;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getSpecialist(): ?Specialist
    {
        return $this->specialist;
    }

    public function setSpecialist(?Specialist $specialist): static
    {
        $this->specialist = $specialist;

        return $this;
    }
    public function getTimeBeforeAppointment(): ?string
    {
        $time_before_appointment = $this->appointment_time->diff(new \DateTimeImmutable('now', new \DateTimeZone('Europe/Vilnius')));
        return $time_before_appointment->format('%d days %h hours %i minutes');
    }

}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Customer;
use App\Repository\CustomerRepository;
use App\Repository\SpecialistRepository;
use App\Service\HolidayApi;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;

use function Zenstruck\Foundry\faker;

class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function homepage():Response
    {
        return $this->render('reservation/homepage.html.twig');    
    }

    #[Route('/reservation', name: 'app_reservation')]
    public function reservation(): Response
    {

        return $this->render('reservation/reservation.html.twig');
    }
    
    #[Route('/reserved', name:'app_reserved')]
    public function reserved(MailerInterface $mailerInterface, EntityManagerInterface $entityManagerInterface, Request $request, HolidayApi $holidayApi, SpecialistRepository $specialistRepository):Response
    {
        $email = $request->request->get('email');
        $customerRepository = $entityManagerInterface->getRepository(Customer::class);
        if(!$customerRepository->findOneBy(['email' => $email]) || in_array($customerRepository->findOneBy( ['email'=>$email])->getState(), ['finished', 'cancelled']))
        {
            if($customerRepository->findAll() == [] || $customerRepository->findBy(['state' => 'reserved']) == null )
            {
                $appointment_time = new DateTime('now', new \DateTimeZone('Europe/Vilnius'));
                $appointment_time->modify('+5 minute');
                $specialist_array= $specialistRepository->findAll();
                $specialist = $specialist_array[array_rand($specialist_array)];
            }
            else
            {
                $latest_customer = $customerRepository->findCustomerWithLatestAppointmentTime();
                $appointment_time = $latest_customer->getAppointmentTime()->modify('+ 30 minutes');
                $specialist = $latest_customer->getSpecialist();
            }
            

            if( ( $appointment_time >= new \DateTime($appointment_time->format('Y-m-d').'19:00:00') ) && ( $appointment_time>=(new \DateTime(($appointment_time->format('Y-m-d'.'06:00:00'))))->modify('+1 day') ) )
            {
                $appointment_time = (new \DateTime(($appointment_time->format('Y-m-d'.'06:00:00'))))->modify('+1 day');
            }


            if($holidayApi->checkIfReservationTimeIsHoliday($appointment_time))
            {
                $appointment_time = $appointment_time->modify('+1 day');
                //return $this->render('reservation/reservation.html.twig', ['holday' => true]);
            }

            $rez_code = $customerRepository->getLatestReservationNrPlusOne();
            
            
            $customer = new Customer();
            $customer->setEmail($request->request->get('email'))
            ->setReservationCode($rez_code)
            ->setState('reserved')
            ->setAppointmentTime($appointment_time)
            ->setSpecialist($specialist);

            $entityManagerInterface->persist($customer);
            $entityManagerInterface->flush();
            $reservation = true;

            $email = (new TemplatedEmail())
            ->to($request->request->get('email'))
            ->subject('Registration confirmation')
            ->htmlTemplate('reservation/reservation_email.html.twig')
            ->context([
                'customer' => $customer 
            ]);
            //dd($email);
            try{
                $mailerInterface->send($email);
            } catch(\Symfony\Component\Mailer\Exception\TransportExceptionInterface $e){
                $error = true;
                return $this->render('reservation/reservation.html.twig', ['error' => $error]);
            }
        }
        else{
            $customer = $customerRepository->findOneBy(['email' => $email]);
            $reservation=false;
            
        }
        

        //Calculation
        //$customer = $customerRepository->findOneBy(['email' => ]);
        
        return $this->render('reservation/reserved.html.twig', ['customer' => $customer, 'reservation' => $reservation]);
    }

    #[Route("/reserved/cancelled",name:"app_cancel_visit")]
    public function cancel_visit(EntityManagerInterface $entityManagerInterface, Request $request):Response
    {
        $email = $request->query->get('email');
        $customer = $entityManagerInterface->getRepository(Customer::class)->findOneBy(['email'=>$email]);
        $customer->setState('cancelled');
        $entityManagerInterface->flush();
        return $this->render('reservation/cancelled.html.twig', ['customer' => $customer]);
    }
    #[Route("/reserved/download-pdf",name:"app_print_pdf")]

    public function download_pdf(Pdf $knpSnappyPdf, Request $request, EntityManagerInterface $entityManagerInterface): PdfResponse
    {
        $email = $request->query->get('email');
        $customer = $entityManagerInterface->getRepository(Customer::class)->findOneBy(['email'=>$email]);
        $html = $this->renderView('reservation/pdf.html.twig',[
            'customer'  => $customer
        ]);

        return new PdfResponse(
            $knpSnappyPdf->getOutputFromHtml($html),
            'reservation.pdf'
        );
    }
}

templates/reservation/cancelled.html.twig
{% extends 'base.html.twig' %}

{% block title %}Complete{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <h1 class="display-4">Visit Canceled</h1>
                    <p class="lead">Your visit has been canceled.</p>
                    <a href="{{ path('app_homepage') }}" class="btn btn-primary">Return to Homepage</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reservation/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block taskbar %}

{% endblock %}

{% block body %}
<div class="container-fluid">
<div class="row">
<div class="col-6 text-end"><h1>Home</h1></div>
<div class="col-5 text-end">
{% if app.user %}
<a href={{path('app_specialist_logout')}} class="btn btn-default" role="button">Logout</a></div>
{% endif %}
</div>
</div>
</div>
<div class="container">
    <div class="row">
        
        
            {% if app.user %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Display screen</h5>
                            <a class="btn btn-default" href={{path('app_display')}}>Go to display</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Management Home</h5>
                            <a class="btn btn-default" href="{{ path('app_management') }}">Go to Management</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Make or check an existing reservation</h5>
                            <a class="btn btn-default" href={{ path('app_reservation') }}>Reserve Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Specialist login</h5>
                            <a class="btn btn-default" href="{{ path('app_specialist_login') }}">Login as Specialist</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        
    </div>
</div>
{% endblock %}

templates/reservation/pdf.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Reservation download pdf</title>
    <style>

        body {
            /*background-color: #f5f5f5;*/

        }
        .card {
            
            background-color: #f8f9fa;
            border: 2px solid #007bff;
            border-radius: 10px;
            margin: 20px;
            padding: 20px;

            position: absolute;
            left: 30%;
            transform: translateX(-50%);

            width: 400px;
            
        }
        .card-title {
            color: #007bff;
            font-size: 2rem;
        }
        .lead {
            color: #343a40;
            font-size: 1.5rem;
        }
        .container {
            max-width: 600px;
            position: relative;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Reservation Complete</h1>
                        <p class="lead">Your Serial Code: <span>{{ customer.reservationCode }}</span></p>
                        <p class="lead">Your Appointment Time: <span>{{ customer.appointmentTime|date('Y-m-d H:i:s') }}</span></p>
                        <p class="lead">Time Left until your appointment:<br> <span><b>{{ customer.TimeBeforeAppointment }} </b></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/reservation/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservations{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
                    {% if error is defined %}
                    <h1> There is a problem with your MESSENGER_DSN key in .env </h1>
                    {% endif %}
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    {% if cancelled is defined %}
                        <p class="alert alert-danger">Visit has been canceled.</p>
                    {% endif %}
                    
                    <h1 class="display-4">Make a Reservation</h1>
                    <form action="{{ path('app_reserved') }}" method="post" class="mt-4">
                        <div class="form-group">
                            <input type="email" name="email" class="form-control" placeholder="Enter your email" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reservation/reservation_email.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Reservation Complete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
        body {
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
            margin-top: 100px;
            padding: 20px;
            border-radius: 10px;
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }
        h2 {
            color: #007bff;
        }
        b.rez-code {
            font-size: 24px;
            color: #15822e;
        }

        .time-left
        {
            font-size: 20px;
            color: #007bff;
        }

    </style>
</head>
<body>
    <div class="container">
        <h2>Reservation Complete</h2>
        <br>
        <font class="time-left">Time left until appointment: <b>{{ customer.getTimeBeforeAppointment}}</b> </font> <br><br>
        <font style="color: #007bff"> Reservation Code<font>
        <b class="rez-code">{{ customer.getReservationCode() }}</b><br>

    </div>
</body>
</html>

templates/reservation/reserved.html.twig
{% extends 'base.html.twig' %}

{% block title %}Complete{% endblock %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-body">
                    <h1 class="display-4">
                        {% if reservation == true %}
                            Reservation Complete
                        {% elseif customer.state == 'current'%}
                            Session in progress
                        {% else %}
                            Reservation Already Made
                        {% endif %}
                    </h1>
                    <p class="lead">
                        Your Serial Code: <b>{{ customer.reservationCode }}</b>
                        <br>
                        Your Appointment Time: <b>{{ customer.appointmentTime|date('Y-m-d H:i:s', "Europe/Vilnius") }}</b> <br>
                        Time Left until your appointment: <b>{{ customer.TimeBeforeAppointment }} </b>
                    </p>
                    <div class="btn-group" role="group">
                        <a href="{{ path('app_cancel_visit', {'email': customer.email}) }}" class="btn btn-danger">Cancel Visit</a>
                        <a href="{{ path('app_print_pdf', {'email': customer.email}) }}" class="btn btn-primary">Download PDF</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}